package Lessons;

public class Problem_02_Even_Fibonacci_numbers {

	/*
	 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
	 * By starting with 1 and 2, the first 10 terms will be:
		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
		
		By considering the terms in the Fibonacci sequence 
		whose values do not exceed four million, find the sum of the even-valued terms.
	 */
	
	public static void main(String[] args) {

		int n = 500000;
		int firstNum = 0;
		int secondNum = 1;
		int output = 0;
		
		for(int i = 0; i < n; i++) {
			int sum = firstNum + secondNum;
			
			firstNum = secondNum;
			secondNum = sum;
			
			if(sum % 2 == 0)
			output += sum;
			
			if(sum >= 4000000) {
				System.out.println(output);
				return;
			}
		}
	}
	
}
